import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.Locale;

/**
 * GUI for the account creation.
 */
public class CreateAccPage extends JPanel {
    private JPanel HomeAndLoginPanel;
    private JPanel optionsBasePanel;
    private JPanel imagePanel;
    private JPanel titlePanel;
    private JLabel titleLbl;
    private JPanel optionsPanel;
    private JLabel title2Panel;
    private JPanel titleTwoPanel;
    private JPanel dividerPanel;
    private JSeparator divider;
    private JPanel btnChoicesPanel;
    private JPanel btnPanel;
    private JPanel loginBtnPanel, createAccPanel;
    private JButton loginBtn, createAccBtn;
    private JPanel previousPanel;
    private JButton returnBtn;
    private JPanel dividePanel, loginLblPanel;
    private JPanel createAccLblPanel;
    private JLabel createAccLbl;
    private JPanel firstNameInputPanel;
    private JLabel firstNameLbl;
    private JTextField firstNameFld;
    private JPanel lastNameInputPanel;
    private JLabel lastNameLbl;
    private JTextField lastNameFld;
    private JTextField birthDayFld, birthYearFld;
    private JComboBox<String> birthMonthPane;
    private JLabel birthMonthLbl, birthDayLbl, birthYearLbl;
    private JLabel genderLbl;
    private JTextField genderFld;
    private JTextField usernameFld;
    private JPasswordField passwordFld, confirmPassFld;
    private JLabel confrimPassLbl;
    private JComboBox<String> types;
    private JComboBox<String> professorTypes;
    private JLabel passReqLbl;
    private JPanel passReqLblPanel;
    private JPanel reqContentsPanel;
    private JTextArea contentsArea;

    public CreateAccPage() {
        setLayout(new BorderLayout());

        setSize(800, 500);

        designPanel();

        setVisible(true);
    }

    private void insertImage() {
        // Load the image
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/SMS-Logo.png"));

        // Scale the image to fit within the panel (adjust dimensions as needed)
        Image image = imageIcon.getImage().getScaledInstance(400, 300, Image.SCALE_SMOOTH); // Example size 100x100
        imageIcon = new ImageIcon(image);

        // Create a JLabel with the scaled image
        JLabel imageLabel = new JLabel(imageIcon);

        // Clear any previous components in imagePanel (optional, but helps avoid duplicates)
        imagePanel.removeAll();
        imagePanel.setBackground(new Color(-331546));

        // Add the image label to the image panel
        imagePanel.add(imageLabel, BorderLayout.CENTER);

        imagePanel.revalidate();
        imagePanel.repaint();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void designPanel() {
        HomeAndLoginPanel = new JPanel();
        HomeAndLoginPanel.setLayout(new BorderLayout(0, 0));
        HomeAndLoginPanel.setBackground(new Color(-331546));
        HomeAndLoginPanel.setEnabled(true);
        HomeAndLoginPanel.setMaximumSize(new Dimension(800, 500));
        HomeAndLoginPanel.setMinimumSize(new Dimension(800, 500));
        HomeAndLoginPanel.setPreferredSize(new Dimension(800, 500));

        optionsBasePanel = new JPanel();
        optionsBasePanel.setLayout(new BorderLayout(0, 0));
        optionsBasePanel.setOpaque(false);
        optionsBasePanel.setPreferredSize(new Dimension(400, 0));
        HomeAndLoginPanel.add(optionsBasePanel, BorderLayout.WEST);
        optionsBasePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20, 5, 20, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        titlePanel = new JPanel();
        titlePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        titlePanel.setBackground(new Color(-4604993));
        titlePanel.setMinimumSize(new Dimension(400, 200));
        titlePanel.setOpaque(false);
        optionsBasePanel.add(titlePanel, BorderLayout.NORTH);
        titlePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.getFont(null, -1, -1, titlePanel.getFont()), null));

        titleLbl = new JLabel();
        Font titleLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 22, titleLbl.getFont());
        if (titleLblFont != null) titleLbl.setFont(titleLblFont);
        titleLbl.setForeground(Color.decode("#FB4570"));
        titleLbl.setText("STUDENT MANAGEMENT");
        titlePanel.add(titleLbl);

        optionsPanel = new JPanel();
        optionsPanel.setLayout(new BorderLayout(0, 0));
        optionsPanel.setOpaque(false);
        optionsBasePanel.add(optionsPanel, BorderLayout.CENTER);
        optionsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        titleTwoPanel = new JPanel();
        titleTwoPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        titleTwoPanel.setOpaque(false);
        optionsPanel.add(titleTwoPanel, BorderLayout.NORTH);
        titleTwoPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        title2Panel = new JLabel();
        Font title2PanelFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 22, title2Panel.getFont());
        if (title2PanelFont != null) title2Panel.setFont(title2PanelFont);
        title2Panel.setForeground(Color.decode("#FB4570"));
        title2Panel.setOpaque(false);
        title2Panel.setText("SYSTEM");
        titleTwoPanel.add(title2Panel);

        dividerPanel = new JPanel();
        dividerPanel.setLayout(new BorderLayout(0, 0));
        dividerPanel.setOpaque(false);
        optionsPanel.add(dividerPanel, BorderLayout.CENTER);
        dividerPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(29, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        dividePanel = new JPanel();
        dividePanel.setLayout(new BorderLayout(0,0));
        dividePanel.setOpaque(false);
        dividerPanel.add(dividePanel, BorderLayout.NORTH);
        dividePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        divider = new JSeparator();
        divider.setForeground(new Color(-16777216));
        divider.setInheritsPopupMenu(false);
        divider.setMinimumSize(new Dimension(1, 1));
        divider.setPreferredSize(new Dimension(0, 3));
        dividePanel.add(divider, BorderLayout.NORTH);

        createAccLblPanel = new JPanel();
        createAccLblPanel.setLayout(new FlowLayout());
        createAccLblPanel.setOpaque(false);
        dividePanel.add(createAccLblPanel, BorderLayout.SOUTH);
        createAccLblPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        createAccLbl = new JLabel();
        createAccLbl.setText("CREATE ACCOUNT");
        Font createAccLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, createAccLbl.getFont());
        if (createAccLblFont != null) createAccLbl.setFont(createAccLblFont);
        createAccLblPanel.add(createAccLbl);

        btnChoicesPanel = new JPanel();
        btnChoicesPanel.setLayout(new BorderLayout(0, 0));
        btnChoicesPanel.setOpaque(false);
        dividerPanel.add(btnChoicesPanel, BorderLayout.CENTER);

        firstNameInputPanel = new JPanel();

        firstNameLbl = new JLabel();

        firstNameFld = new JTextField();

        btnChoicesPanel.add(firstNameInputPanel, BorderLayout.NORTH);

        lastNameInputPanel = new JPanel();

        lastNameLbl = new JLabel();

        lastNameFld = new JTextField();

        btnPanel = new JPanel();

        loginBtnPanel = new JPanel();

        loginBtn = new JButton();

        createAccPanel = new JPanel();

        createAccBtn = new JButton();

        previousPanel = new JPanel();
        previousPanel.setLayout(new BorderLayout(0,0));
        previousPanel.setOpaque(false);
        btnChoicesPanel.add(previousPanel, BorderLayout.SOUTH);

        returnBtn = new JButton();
        returnBtn.setBackground(Color.decode("#000040"));
        returnBtn.setBorderPainted(true);
        returnBtn.setContentAreaFilled(true);
        Font returnBtnFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 14, returnBtn.getFont());
        if (returnBtnFont != null) returnBtn.setFont(returnBtnFont);
        returnBtn.setForeground(Color.decode("#000000"));
        returnBtn.setOpaque(false);
        returnBtn.setPreferredSize(new Dimension(130, 30));
        returnBtn.setSelected(false);
        returnBtn.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0,0,10,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        returnBtn.setText("< RETURN");
        previousPanel.add(returnBtn, BorderLayout.WEST);

        imagePanel = new JPanel();
        imagePanel.setLayout(new BorderLayout(0, 0));
        imagePanel.setBorder(BorderFactory.createEmptyBorder());
        imagePanel.setOpaque(false);
        insertImage();

        passReqLblPanel = new JPanel();

        passReqLbl = new JLabel();

        reqContentsPanel = new JPanel();

        contentsArea = new JTextArea();

        HomeAndLoginPanel.add(imagePanel, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    private Font getFont(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent getRootComponent() {
        return HomeAndLoginPanel;
    }

    public void setActionListener(ActionListener listener) {
        loginBtn.addActionListener(listener);
        createAccBtn.addActionListener(listener);
        returnBtn.addActionListener(listener);
    }

    private void reinitializeReset() {
        createAccPanel = new JPanel();
        createAccPanel.setLayout(new FlowLayout());
        createAccPanel.setOpaque(false);
        createAccPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnPanel.add(createAccPanel, BorderLayout.SOUTH);

        createAccBtn.setBackground(Color.decode("#000040"));
        createAccBtn.setBorderPainted(true);
        createAccBtn.setContentAreaFilled(true);
        Font createAccBtnFont = this.getFont("Microsoft Sans Serif", Font.PLAIN, 10, createAccBtn.getFont());
        if (createAccBtnFont != null) createAccBtn.setFont(createAccBtnFont);
        createAccBtn.setForeground(new Color(-5103070));
        createAccBtn.setOpaque(false);
        createAccBtn.setPreferredSize(new Dimension(200, 30));
        createAccBtn.setSelected(false);
        createAccBtn.setText("Reset Inputs");
        createAccBtn.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        createAccPanel.add(createAccBtn);
    }

    private void reinitializeLogin(String title) {
        loginBtnPanel = new JPanel();
        loginBtnPanel.setLayout(new FlowLayout());
        loginBtnPanel.setOpaque(false);
        loginBtnPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnPanel.add(loginBtnPanel, BorderLayout.NORTH);

        loginBtn.setBackground(Color.decode("#000040"));
        loginBtn.setBorderPainted(true);
        loginBtn.setContentAreaFilled(true);
        Font loginBtnFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, loginBtn.getFont());
        if (loginBtnFont != null) loginBtn.setFont(loginBtnFont);
        loginBtn.setForeground(new Color(-331546));
        loginBtn.setOpaque(true);
        loginBtn.setPreferredSize(new Dimension(200, 30));
        loginBtn.setSelected(false);
        loginBtn.setText(title);
        loginBtnPanel.add(loginBtn);
    }

    public void updateForStepOneTeacher(String[] profTypes) {
        setLoginPageLbl("NEW TEACHER");

        firstNameInputPanel.removeAll();
        lastNameInputPanel.removeAll();

        insertImage();

        firstNameInputPanel = new JPanel();
        firstNameInputPanel.setLayout(new FlowLayout());
        firstNameInputPanel.setOpaque(false);
        firstNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        firstNameLbl = new JLabel();
        firstNameLbl.setText("FIRST NAME: ");
        Font firstNameLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, firstNameLbl.getFont());
        if (firstNameLblFont != null) firstNameLbl.setFont(firstNameLblFont);
        firstNameInputPanel.add(firstNameLbl);

        firstNameFld = new JTextField();
        firstNameFld.setBackground(new Color(-2104859));
        firstNameFld.setColumns(25);
        firstNameFld.setHorizontalAlignment(10);
        firstNameInputPanel.add(firstNameFld);

        btnChoicesPanel.add(firstNameInputPanel, BorderLayout.NORTH);

        lastNameInputPanel = new JPanel();
        lastNameInputPanel.setLayout(new FlowLayout());
        lastNameInputPanel.setOpaque(false);
        lastNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnChoicesPanel.add(lastNameInputPanel, BorderLayout.CENTER);

        lastNameLbl = new JLabel();
        lastNameLbl.setText("LAST NAME: ");
        Font lastNameLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, lastNameLbl.getFont());
        if (lastNameLblFont != null) lastNameLbl.setFont(lastNameLblFont);
        lastNameInputPanel.add(lastNameLbl);

        lastNameFld = new JTextField();
        lastNameFld.setBackground(new Color(-2104859));
        lastNameFld.setColumns(25);
        lastNameFld.setHorizontalAlignment(10);
        lastNameInputPanel.add(lastNameFld);

        confrimPassLbl = new JLabel();
        confrimPassLbl.setText("PROFESSOR/LECTURER TYPE: ");
        Font confrimPassLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, confrimPassLbl.getFont());
        if (confrimPassLblFont != null) confrimPassLbl.setFont(confrimPassLblFont);
        lastNameInputPanel.add(confrimPassLbl);

        professorTypes = new JComboBox<>(profTypes);
        professorTypes.setBackground(new Color(-2104859));
        lastNameInputPanel.add(professorTypes);

        btnPanel = new JPanel();
        btnPanel.setLayout(new BorderLayout(0,0));
        btnPanel.setOpaque(false);
        btnPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(35,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lastNameInputPanel.add(btnPanel, BorderLayout.SOUTH);

        reinitializeLogin("Proceed To Step 2 of 3");

        reinitializeReset();

        revalidate();
        repaint();
    }

    public void updateForStepOneStudent(String[] years) {
        setLoginPageLbl("NEW STUDENT");

        firstNameInputPanel.removeAll();
        lastNameInputPanel.removeAll();

        insertImage();

        firstNameInputPanel = new JPanel();
        firstNameInputPanel.setLayout(new FlowLayout());
        firstNameInputPanel.setOpaque(false);
        firstNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        firstNameLbl = new JLabel();
        firstNameLbl.setText("FIRST NAME: ");
        Font firstNameLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, firstNameLbl.getFont());
        if (firstNameLblFont != null) firstNameLbl.setFont(firstNameLblFont);
        firstNameInputPanel.add(firstNameLbl);

        firstNameFld = new JTextField();
        firstNameFld.setBackground(new Color(-2104859));
        firstNameFld.setColumns(25);
        firstNameFld.setHorizontalAlignment(10);
        firstNameInputPanel.add(firstNameFld);

        btnChoicesPanel.add(firstNameInputPanel, BorderLayout.NORTH);

        lastNameInputPanel = new JPanel();
        lastNameInputPanel.setLayout(new FlowLayout());
        lastNameInputPanel.setOpaque(false);
        lastNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnChoicesPanel.add(lastNameInputPanel, BorderLayout.CENTER);

        lastNameLbl = new JLabel();
        lastNameLbl.setText("LAST NAME: ");
        Font lastNameLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, lastNameLbl.getFont());
        if (lastNameLblFont != null) lastNameLbl.setFont(lastNameLblFont);
        lastNameInputPanel.add(lastNameLbl);

        lastNameFld = new JTextField();
        lastNameFld.setBackground(new Color(-2104859));
        lastNameFld.setColumns(25);
        lastNameFld.setHorizontalAlignment(10);
        lastNameInputPanel.add(lastNameFld);

        confrimPassLbl = new JLabel();
        confrimPassLbl.setText("STUDENT YEAR: ");
        Font confrimPassLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, confrimPassLbl.getFont());
        if (confrimPassLblFont != null) confrimPassLbl.setFont(confrimPassLblFont);
        lastNameInputPanel.add(confrimPassLbl);

        types = new JComboBox<>(years);
        types.setBackground(new Color(-2104859));
        lastNameInputPanel.add(types);

        btnPanel = new JPanel();
        btnPanel.setLayout(new BorderLayout(0,0));
        btnPanel.setOpaque(false);
        btnPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(35,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lastNameInputPanel.add(btnPanel, BorderLayout.SOUTH);

        reinitializeLogin("Proceed To Step 2 of 3");

        reinitializeReset();

        revalidate();
        repaint();
    }

    public void updateForStepTwoStudent(String[] months) {
        setLoginPageLbl("BIRTHDATE AND GENDER (STUDENT)");

        firstNameInputPanel.removeAll();
        lastNameInputPanel.removeAll();

        insertImage();

        birthMonthLbl = new JLabel();
        birthMonthLbl.setText("MONTH: ");
        Font birthMonthLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, birthMonthLbl.getFont());
        if (birthMonthLblFont != null) birthMonthLbl.setFont(birthMonthLblFont);
        firstNameInputPanel.add(birthMonthLbl);

        birthMonthPane = new JComboBox<>(months);
        birthMonthPane.setBackground(new Color(-2104859));
        firstNameInputPanel.add(birthMonthPane);

        birthDayLbl = new JLabel();
        birthDayLbl.setText("DAY: ");
        Font birthDayLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, birthDayLbl.getFont());
        if (birthDayLblFont != null) birthDayLbl.setFont(birthDayLblFont);
        firstNameInputPanel.add(birthDayLbl);

        birthDayFld = new JTextField();
        birthDayFld.setBackground(new Color(-2104859));
        birthDayFld.setColumns(5);
        birthDayFld.setHorizontalAlignment(10);
        firstNameInputPanel.add(birthDayFld);

        birthYearLbl = new JLabel();
        birthYearLbl.setText("YEAR: ");
        Font birthYearLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, birthYearLbl.getFont());
        if (birthDayLblFont != null) birthYearLbl.setFont(birthYearLblFont);
        firstNameInputPanel.add(birthYearLbl);

        birthYearFld = new JTextField();
        birthYearFld.setBackground(new Color(-2104859));
        birthYearFld.setColumns(5);
        birthYearFld.setHorizontalAlignment(10);
        firstNameInputPanel.add(birthYearFld);

        btnChoicesPanel.add(firstNameInputPanel, BorderLayout.NORTH);

        lastNameInputPanel = new JPanel();
        lastNameInputPanel.setLayout(new FlowLayout());
        lastNameInputPanel.setOpaque(false);
        lastNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnChoicesPanel.add(lastNameInputPanel, BorderLayout.CENTER);

        genderLbl = new JLabel();
        genderLbl.setText("GENDER: ");
        Font genderLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, genderLbl.getFont());
        if (genderLblFont != null) genderLbl.setFont(genderLblFont);
        lastNameInputPanel.add(genderLbl);

        genderFld = new JTextField();
        genderFld.setBackground(new Color(-2104859));
        genderFld.setColumns(25);
        genderFld.setHorizontalAlignment(10);
        lastNameInputPanel.add(genderFld);

        btnPanel = new JPanel();
        btnPanel.setLayout(new BorderLayout(0,0));
        btnPanel.setOpaque(false);
        btnPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(35,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lastNameInputPanel.add(btnPanel, BorderLayout.SOUTH);

        reinitializeLogin("Proceed To Step 3 of 3");

        reinitializeReset();

        revalidate();
        repaint();
    }

    public void updateForStepTwoTeacher(String[] months) {
        setLoginPageLbl("BIRTHDATE AND GENDER (TEACHER)");

        firstNameInputPanel.removeAll();
        lastNameInputPanel.removeAll();

        insertImage();

        birthMonthLbl = new JLabel();
        birthMonthLbl.setText("MONTH: ");
        Font birthMonthLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, birthMonthLbl.getFont());
        if (birthMonthLblFont != null) birthMonthLbl.setFont(birthMonthLblFont);
        firstNameInputPanel.add(birthMonthLbl);

        birthMonthPane = new JComboBox<>(months);
        birthMonthPane.setBackground(new Color(-2104859));
        firstNameInputPanel.add(birthMonthPane);

        birthDayLbl = new JLabel();
        birthDayLbl.setText("DAY: ");
        Font birthDayLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, birthDayLbl.getFont());
        if (birthDayLblFont != null) birthDayLbl.setFont(birthDayLblFont);
        firstNameInputPanel.add(birthDayLbl);

        birthDayFld = new JTextField();
        birthDayFld.setBackground(new Color(-2104859));
        birthDayFld.setColumns(5);
        birthDayFld.setHorizontalAlignment(10);
        firstNameInputPanel.add(birthDayFld);

        birthYearLbl = new JLabel();
        birthYearLbl.setText("YEAR: ");
        Font birthYearLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, birthYearLbl.getFont());
        if (birthDayLblFont != null) birthYearLbl.setFont(birthYearLblFont);
        firstNameInputPanel.add(birthYearLbl);

        birthYearFld = new JTextField();
        birthYearFld.setBackground(new Color(-2104859));
        birthYearFld.setColumns(5);
        birthYearFld.setHorizontalAlignment(10);
        firstNameInputPanel.add(birthYearFld);

        btnChoicesPanel.add(firstNameInputPanel, BorderLayout.NORTH);

        lastNameInputPanel = new JPanel();
        lastNameInputPanel.setLayout(new FlowLayout());
        lastNameInputPanel.setOpaque(false);
        lastNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnChoicesPanel.add(lastNameInputPanel, BorderLayout.CENTER);

        genderLbl = new JLabel();
        genderLbl.setText("GENDER: ");
        Font genderLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, genderLbl.getFont());
        if (genderLblFont != null) genderLbl.setFont(genderLblFont);
        lastNameInputPanel.add(genderLbl);

        genderFld = new JTextField();
        genderFld.setBackground(new Color(-2104859));
        genderFld.setColumns(25);
        genderFld.setHorizontalAlignment(10);
        lastNameInputPanel.add(genderFld);

        btnPanel = new JPanel();
        btnPanel.setLayout(new BorderLayout(0,0));
        btnPanel.setOpaque(false);
        btnPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(35,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lastNameInputPanel.add(btnPanel, BorderLayout.SOUTH);

        reinitializeLogin("Proceed To Step 3 of 3");

        reinitializeReset();

        revalidate();
        repaint();
    }

    public void updateForLastStepTeacher() {
        setLoginPageLbl("USERNAME AND PASSWORD (TEACHER)");

        firstNameInputPanel.removeAll();
        lastNameInputPanel.removeAll();

        showPasswordRequirements();

        firstNameInputPanel = new JPanel();
        firstNameInputPanel.setLayout(new FlowLayout());
        firstNameInputPanel.setOpaque(false);
        firstNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        firstNameLbl = new JLabel();
        firstNameLbl.setText("USERNAME: ");
        Font firstNameLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, firstNameLbl.getFont());
        if (firstNameLblFont != null) firstNameLbl.setFont(firstNameLblFont);
        firstNameInputPanel.add(firstNameLbl);

        usernameFld = new JTextField();
        usernameFld.setBackground(new Color(-2104859));
        usernameFld.setColumns(25);
        usernameFld.setHorizontalAlignment(10);
        firstNameInputPanel.add(usernameFld);

        btnChoicesPanel.add(firstNameInputPanel, BorderLayout.NORTH);

        lastNameInputPanel = new JPanel();
        lastNameInputPanel.setLayout(new FlowLayout());
        lastNameInputPanel.setOpaque(false);
        lastNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnChoicesPanel.add(lastNameInputPanel, BorderLayout.CENTER);

        lastNameLbl = new JLabel();
        lastNameLbl.setText("PASSWORD: ");
        Font lastNameLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, lastNameLbl.getFont());
        if (lastNameLblFont != null) lastNameLbl.setFont(lastNameLblFont);
        lastNameInputPanel.add(lastNameLbl);

        passwordFld = new JPasswordField();
        passwordFld.setBackground(new Color(-2104859));
        passwordFld.setColumns(25);
        passwordFld.setHorizontalAlignment(10);
        lastNameInputPanel.add(passwordFld);

        confrimPassLbl = new JLabel();
        confrimPassLbl.setText("CONFIRM PASSWORD: ");
        Font confrimPassLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, confrimPassLbl.getFont());
        if (confrimPassLblFont != null) confrimPassLbl.setFont(confrimPassLblFont);
        lastNameInputPanel.add(confrimPassLbl);

        confirmPassFld = new JPasswordField();
        confirmPassFld.setBackground(new Color(-2104859));
        confirmPassFld.setColumns(19);
        confirmPassFld.setHorizontalAlignment(10);
        lastNameInputPanel.add(confirmPassFld);

        btnPanel = new JPanel();
        btnPanel.setLayout(new BorderLayout(0,0));
        btnPanel.setOpaque(false);
        btnPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(30,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lastNameInputPanel.add(btnPanel, BorderLayout.SOUTH);

        reinitializeLogin("SIGN UP");

        reinitializeReset();

        revalidate();
        repaint();
    }

    public void updateForLastStepStudent() {
        setLoginPageLbl("ID NUMBER AND PASSWORD (STUDENT)");

        firstNameInputPanel.removeAll();
        lastNameInputPanel.removeAll();

        showPasswordRequirements();

        firstNameInputPanel = new JPanel();
        firstNameInputPanel.setLayout(new FlowLayout());
        firstNameInputPanel.setOpaque(false);
        firstNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        firstNameLbl = new JLabel();
        firstNameLbl.setText("ID NUMBER (USERNAME): ");
        Font firstNameLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, firstNameLbl.getFont());
        if (firstNameLblFont != null) firstNameLbl.setFont(firstNameLblFont);
        firstNameInputPanel.add(firstNameLbl);

        usernameFld = new JTextField();
        usernameFld.setBackground(new Color(-2104859));
        usernameFld.setColumns(17);
        usernameFld.setHorizontalAlignment(10);
        firstNameInputPanel.add(usernameFld);

        btnChoicesPanel.add(firstNameInputPanel, BorderLayout.NORTH);

        lastNameInputPanel = new JPanel();
        lastNameInputPanel.setLayout(new FlowLayout());
        lastNameInputPanel.setOpaque(false);
        lastNameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnChoicesPanel.add(lastNameInputPanel, BorderLayout.CENTER);

        lastNameLbl = new JLabel();
        lastNameLbl.setText("PASSWORD: ");
        Font lastNameLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, lastNameLbl.getFont());
        if (lastNameLblFont != null) lastNameLbl.setFont(lastNameLblFont);
        lastNameInputPanel.add(lastNameLbl);

        passwordFld = new JPasswordField();
        passwordFld.setBackground(new Color(-2104859));
        passwordFld.setColumns(25);
        passwordFld.setHorizontalAlignment(10);
        lastNameInputPanel.add(passwordFld);

        confrimPassLbl = new JLabel();
        confrimPassLbl.setText("CONFIRM PASSWORD: ");
        Font confrimPassLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, confrimPassLbl.getFont());
        if (confrimPassLblFont != null) confrimPassLbl.setFont(confrimPassLblFont);
        lastNameInputPanel.add(confrimPassLbl);

        confirmPassFld = new JPasswordField();
        confirmPassFld.setBackground(new Color(-2104859));
        confirmPassFld.setColumns(19);
        confirmPassFld.setHorizontalAlignment(10);
        lastNameInputPanel.add(confirmPassFld);

        btnPanel = new JPanel();
        btnPanel.setLayout(new BorderLayout(0,0));
        btnPanel.setOpaque(false);
        btnPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(30,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lastNameInputPanel.add(btnPanel, BorderLayout.SOUTH);

        reinitializeLogin("SIGN UP");

        reinitializeReset();

        revalidate();
        repaint();
    }

    public void setLoginPageLbl(String title) {
        createAccLbl.setText(title);
    }

    public String getFirstName() {
        return firstNameFld.getText();
    }

    public String getLastName() {
        return lastNameFld.getText();
    }

    public String getProfType() {
        return (String) professorTypes.getSelectedItem();
    }

    public String getStudentYear() {
        return (String) types.getSelectedItem();
    }

    public String getMonth() {
        return (String) birthMonthPane.getSelectedItem();
    }

    public int getDay() {
        try {
            return Integer.parseInt(birthDayFld.getText());
        } catch (NumberFormatException e){
            return 0;
        }
    }

    public int getYear() {
        try {
            return Integer.parseInt(birthYearFld.getText());
        } catch (NumberFormatException e){
            return 0;
        }
    }

    public String getGender() {
        return genderFld.getText();
    }

    public String getUsername() {
        return usernameFld.getText();
    }

    public String getPassword() {
        return Arrays.toString(passwordFld.getPassword());
    }

    public String getConfirmPass() {
        return Arrays.toString(confirmPassFld.getPassword());
    }

    public void clearNameFlds() {
        firstNameFld.setText("");
        lastNameFld.setText("");
    }

    public void clearBirthdateGender() {
        birthMonthPane.setSelectedIndex(0);
        birthDayFld.setText("");
        birthYearFld.setText("");
        genderFld.setText("");
    }

    public void clearUserPass() {
        usernameFld.setText("");
        passwordFld.setText("");
        confirmPassFld.setText("");
    }

    public String getStepLabel() {
        return createAccLbl.getText();
    }

    public void setErrorMessage(String errorMessage) {
        JOptionPane.showMessageDialog(HomeAndLoginPanel, errorMessage, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void setValidMessage(String validMessage) {
        JOptionPane.showMessageDialog(HomeAndLoginPanel, validMessage, "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
    }

    public int showConfirmReturn() {
        return JOptionPane.showConfirmDialog(HomeAndLoginPanel, "Are you sure you want to return to the Sign Up Page?", "CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    }

    public int getYesOption() {
        return JOptionPane.YES_OPTION;
    }

    public int getNoOption() {
        return JOptionPane.NO_OPTION;
    }

    public void showPasswordRequirements() {
        imagePanel.removeAll();

        imagePanel.setLayout(new BorderLayout(0, 0));
        imagePanel.setBorder(BorderFactory.createEmptyBorder());
        imagePanel.setOpaque(false);

        passReqLblPanel.setLayout(new BorderLayout());
        passReqLblPanel.setPreferredSize(new Dimension(380, 150));
        passReqLblPanel.setOpaque(false);
        passReqLblPanel.setBorder(BorderFactory.createEmptyBorder());
        imagePanel.add(passReqLblPanel, BorderLayout.NORTH);

        Font passReqLblFont = this.getFont("Inter Semi Bold", Font.BOLD, 28, passReqLbl.getFont());
        if (passReqLblFont != null) passReqLbl.setFont(passReqLblFont);
        passReqLbl.setForeground(new Color(-16777216));
        passReqLbl.setBorder(BorderFactory.createEmptyBorder(0,0,10,0));
        passReqLbl.setText("| Password Requirements");
        passReqLblPanel.add(passReqLbl, BorderLayout.CENTER);

        reqContentsPanel.setLayout(new BorderLayout());
        reqContentsPanel.setBorder(BorderFactory.createEmptyBorder());
        reqContentsPanel.setOpaque(false);
        imagePanel.add(reqContentsPanel, BorderLayout.CENTER);

        contentsArea.setMargin(new Insets(45,25,25,25));
        contentsArea.setText(" Minimum of 8 characters\n\n" +
                " Must contain at least one number/digit.\n\n" +
                " Must contain at least one uppercase letter.\n\n" +
                " Must contain at least one of the following symbols. (!, *, :, %, #)\n\n" +
                " NOTE: Your password can not be changed after creating your account.");
        Font contentsFont = this.getFont("Microsoft Sans Serif", Font.PLAIN, 16, contentsArea.getFont());
        if (contentsFont != null) contentsArea.setFont(contentsFont);
        contentsArea.setOpaque(false);
        contentsArea.setWrapStyleWord(true);
        contentsArea.setLineWrap(true);
        contentsArea.setEditable(false);
        reqContentsPanel.add(contentsArea);

        revalidate();
        repaint();
    }
}
