import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.Locale;

/**
 * GUI for the loginpage.
 */
public class LoginPage extends JPanel {
    private JPanel HomeAndLoginPanel;
    private JPanel optionsBasePanel;
    private JPanel imagePanel;
    private JPanel titlePanel;
    private JLabel titleLbl;
    private JPanel optionsPanel;
    private JLabel title2Panel;
    private JPanel titleTwoPanel;
    private JPanel dividerPanel;
    private JSeparator divider;
    private JPanel btnChoicesPanel;
    private JLabel usernameLbl, passwordLbl;
    private JPanel usernameInputPanel;
    private JPanel passwordInputPanel;
    private JTextField usernameFld;
    private JPasswordField passwordFld;
    private JPanel btnPanel;
    private JPanel loginBtnPanel, createAccPanel;
    private JButton loginBtn, createAccBtn;
    private JPanel previousPanel;
    private JButton returnBtn;
    private JLabel loginPageLbl;
    private JPanel dividePanel, loginLblPanel;

    public LoginPage() {
        setLayout(new BorderLayout());

        setSize(800, 500);

        designPanel();

        setVisible(true);
    }

    private void insertImage() {
        // Load the image
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/SMS-Logo.png"));

        // Scale the image to fit within the panel (adjust dimensions as needed)
        Image image = imageIcon.getImage().getScaledInstance(400, 300, Image.SCALE_SMOOTH); // Example size 100x100
        imageIcon = new ImageIcon(image);

        // Create a JLabel with the scaled image
        JLabel imageLabel = new JLabel(imageIcon);

        // Clear any previous components in imagePanel (optional, but helps avoid duplicates)
        imagePanel.removeAll();
        imagePanel.setBackground(new Color(-331546));

        // Add the image label to the image panel
        imagePanel.add(imageLabel, BorderLayout.CENTER);

        imagePanel.revalidate();
        imagePanel.repaint();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void designPanel() {
        HomeAndLoginPanel = new JPanel();
        HomeAndLoginPanel.setLayout(new BorderLayout(0, 0));
        HomeAndLoginPanel.setBackground(new Color(-331546));
        HomeAndLoginPanel.setEnabled(true);
        HomeAndLoginPanel.setMaximumSize(new Dimension(800, 500));
        HomeAndLoginPanel.setMinimumSize(new Dimension(800, 500));
        HomeAndLoginPanel.setPreferredSize(new Dimension(800, 500));

        optionsBasePanel = new JPanel();
        optionsBasePanel.setLayout(new BorderLayout(0, 0));
        optionsBasePanel.setOpaque(false);
        optionsBasePanel.setPreferredSize(new Dimension(400, 0));
        HomeAndLoginPanel.add(optionsBasePanel, BorderLayout.WEST);
        optionsBasePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20, 5, 20, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        titlePanel = new JPanel();
        titlePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        titlePanel.setBackground(new Color(-4604993));
        titlePanel.setMinimumSize(new Dimension(400, 200));
        titlePanel.setOpaque(false);
        optionsBasePanel.add(titlePanel, BorderLayout.NORTH);
        titlePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.getFont(null, -1, -1, titlePanel.getFont()), null));

        titleLbl = new JLabel();
        Font titleLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 22, titleLbl.getFont());
        if (titleLblFont != null) titleLbl.setFont(titleLblFont);
        titleLbl.setForeground(Color.decode("#FB4570"));
        titleLbl.setText("STUDENT MANAGEMENT");
        titlePanel.add(titleLbl);

        optionsPanel = new JPanel();
        optionsPanel.setLayout(new BorderLayout(0, 0));
        optionsPanel.setOpaque(false);
        optionsBasePanel.add(optionsPanel, BorderLayout.CENTER);
        optionsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        titleTwoPanel = new JPanel();
        titleTwoPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        titleTwoPanel.setOpaque(false);
        optionsPanel.add(titleTwoPanel, BorderLayout.NORTH);
        titleTwoPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        title2Panel = new JLabel();
        Font title2PanelFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 22, title2Panel.getFont());
        if (title2PanelFont != null) title2Panel.setFont(title2PanelFont);
        title2Panel.setForeground(Color.decode("#FB4570"));
        title2Panel.setOpaque(false);
        title2Panel.setText("SYSTEM");
        titleTwoPanel.add(title2Panel);

        dividerPanel = new JPanel();
        dividerPanel.setLayout(new BorderLayout(0, 0));
        dividerPanel.setOpaque(false);
        optionsPanel.add(dividerPanel, BorderLayout.CENTER);
        dividerPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(29, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        dividePanel = new JPanel();
        dividePanel.setLayout(new BorderLayout(0,0));
        dividePanel.setOpaque(false);
        dividerPanel.add(dividePanel, BorderLayout.NORTH);
        dividePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        divider = new JSeparator();
        divider.setForeground(new Color(-16777216));
        divider.setInheritsPopupMenu(false);
        divider.setMinimumSize(new Dimension(1, 1));
        divider.setPreferredSize(new Dimension(0, 3));
        dividePanel.add(divider, BorderLayout.NORTH);

        loginLblPanel = new JPanel();
        loginLblPanel.setLayout(new FlowLayout());
        loginLblPanel.setOpaque(false);
        dividePanel.add(loginLblPanel, BorderLayout.SOUTH);
        loginLblPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        loginPageLbl = new JLabel();
        loginPageLbl.setText("");
        Font loginPageLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, loginPageLbl.getFont());
        if (loginPageLblFont != null) loginPageLbl.setFont(loginPageLblFont);
        loginLblPanel.add(loginPageLbl);

        btnChoicesPanel = new JPanel();
        btnChoicesPanel.setLayout(new BorderLayout(0, 0));
        btnChoicesPanel.setOpaque(false);
        dividerPanel.add(btnChoicesPanel, BorderLayout.CENTER);

        usernameInputPanel = new JPanel();
        usernameInputPanel.setLayout(new FlowLayout());
        usernameInputPanel.setOpaque(false);
        usernameInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        usernameLbl = new JLabel();
        usernameLbl.setText("USERNAME: ");
        Font usernameLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, usernameLbl.getFont());
        if (usernameLblFont != null) usernameLbl.setFont(usernameLblFont);
        usernameInputPanel.add(usernameLbl);

        usernameFld = new JTextField();
        usernameFld.setBackground(new Color(-2104859));
        usernameFld.setColumns(25);
        usernameFld.setHorizontalAlignment(10);
        usernameInputPanel.add(usernameFld);

        btnChoicesPanel.add(usernameInputPanel, BorderLayout.NORTH);

        passwordInputPanel = new JPanel();
        passwordInputPanel.setLayout(new FlowLayout());
        passwordInputPanel.setOpaque(false);
        passwordInputPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(30,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnChoicesPanel.add(passwordInputPanel, BorderLayout.CENTER);

        passwordLbl = new JLabel();
        passwordLbl.setText("PASSWORD: ");
        Font passwordLblFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, passwordLbl.getFont());
        if (passwordLblFont != null) passwordLbl.setFont(passwordLblFont);
        passwordInputPanel.add(passwordLbl);

        passwordFld = new JPasswordField();
        passwordFld.setBackground(new Color(-2104859));
        passwordFld.setColumns(25);
        passwordFld.setHorizontalAlignment(10);
        passwordInputPanel.add(passwordFld);

        btnPanel = new JPanel();
        btnPanel.setLayout(new BorderLayout(0,0));
        btnPanel.setOpaque(false);
        btnPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(35,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        passwordInputPanel.add(btnPanel, BorderLayout.SOUTH);

        loginBtnPanel = new JPanel();
        loginBtnPanel.setLayout(new FlowLayout());
        loginBtnPanel.setOpaque(false);
        loginBtnPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnPanel.add(loginBtnPanel, BorderLayout.NORTH);

        loginBtn = new JButton();
        loginBtn.setBackground(Color.decode("#000040"));
        loginBtn.setBorderPainted(true);
        loginBtn.setContentAreaFilled(true);
        Font loginBtnFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 12, loginBtn.getFont());
        if (loginBtnFont != null) loginBtn.setFont(loginBtnFont);
        loginBtn.setForeground(new Color(-331546));
        loginBtn.setOpaque(true);
        loginBtn.setPreferredSize(new Dimension(108, 30));
        loginBtn.setSelected(false);
        loginBtn.setText("LOGIN");
        loginBtnPanel.add(loginBtn);

        createAccPanel = new JPanel();
        createAccPanel.setLayout(new FlowLayout());
        createAccPanel.setOpaque(false);
        createAccPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnPanel.add(createAccPanel, BorderLayout.SOUTH);

        createAccBtn = new JButton();
        createAccBtn.setBackground(Color.decode("#000040"));
        createAccBtn.setBorderPainted(true);
        createAccBtn.setContentAreaFilled(true);
        Font createAccBtnFont = this.getFont("Microsoft Sans Serif", Font.PLAIN, 10, createAccBtn.getFont());
        if (createAccBtnFont != null) createAccBtn.setFont(createAccBtnFont);
        createAccBtn.setForeground(new Color(-5103070));
        createAccBtn.setOpaque(false);
        createAccBtn.setPreferredSize(new Dimension(200, 30));
        createAccBtn.setSelected(false);
        createAccBtn.setText("New Here? Sign Up!");
        createAccBtn.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0,0,0,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        createAccPanel.add(createAccBtn);

        previousPanel = new JPanel();
        previousPanel.setLayout(new BorderLayout(0,0));
        previousPanel.setOpaque(false);
        btnChoicesPanel.add(previousPanel, BorderLayout.SOUTH);

        returnBtn = new JButton();
        returnBtn.setBackground(Color.decode("#000040"));
        returnBtn.setBorderPainted(true);
        returnBtn.setContentAreaFilled(true);
        Font returnBtnFont = this.getFont("Microsoft Sans Serif", Font.BOLD, 14, returnBtn.getFont());
        if (returnBtnFont != null) returnBtn.setFont(returnBtnFont);
        returnBtn.setForeground(Color.decode("#000000"));
        returnBtn.setOpaque(false);
        returnBtn.setPreferredSize(new Dimension(130, 30));
        returnBtn.setSelected(false);
        returnBtn.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0,0,10,0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        returnBtn.setText("< RETURN");
        previousPanel.add(returnBtn, BorderLayout.WEST);

        imagePanel = new JPanel();
        imagePanel.setLayout(new BorderLayout(0, 0));
        insertImage();

        HomeAndLoginPanel.add(imagePanel, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    private Font getFont(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent getRootComponent() {
        return HomeAndLoginPanel;
    }

    public void setActionListener(ActionListener listener) {
        loginBtn.addActionListener(listener);
        createAccBtn.addActionListener(listener);
        returnBtn.addActionListener(listener);
    }

    public void setLoginPageLbl(String title) {
        loginPageLbl.setText(title);
        revalidate();
        repaint();
    }

    public String getLoginPageLbl() {
        return loginPageLbl.getText();
    }

    public String getUsername() {
        return usernameFld.getText();
    }

    public String getPassword() {
        return Arrays.toString(passwordFld.getPassword());
    }

    public void clearTextFlds() {
        usernameFld.setText("");
        passwordFld.setText("");
    }

    public void setCreateAccBtnEnabled(boolean enabled) {
        createAccBtn.setEnabled(enabled);
    }

    public void setCreateAccBtnText(String text) {
        createAccBtn.setText(text);
    }

    public void setErrorMessage(String errorMessage) {
        JOptionPane.showMessageDialog(HomeAndLoginPanel, errorMessage, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void setValidMessage(String validMessage) {
        JOptionPane.showMessageDialog(HomeAndLoginPanel, validMessage, "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
    }
}
